token:
  expiration_time: 86400000 # 1day
  secret: '{cipher}AQCsK2uPyxIBEObHn3l7LrxPehaPNB6mhY0YzMZUd9RDx/YbADI5ucoCrJKoCEva6AQPR2zI0t77SFPBimjqWeeJmNyZB5UOpZ+T1Mj6SZUnns/lUsOfkUa53vU2gpqT/GMekndN4KVr/nsiHp4tuFfj0by+UJfxGMi7YVaeNJBQ0YyR/kPNBNgtRPHc5edMqk2DxGJQhCaJBm69eLDTDpyFXbmHQBjoTBcADcbZbaSov7/Xk722HjgjfVSEJhtDXhSyAC3SSKuou0jky+5ZY/YTnCkCjFfcaWee9tvSBTCmFjE1PcCtTjyy3df+1CdYUrUaKESxKuTyq9Zva8qVvaEYs320Y+Xyz8ivebPlqRMppb3jPLOPpJbLxct+fLvBPwkrgI39/81syrS2jLsk8MOM97M9ima06RzKl/ZOZ3zt7xlfpzj1dRRElM+aMvNaTPpJjGE/pmGZChVUOecII6dok3ay5+4MOIVJfarj0yoAaP7STKu3mQG/bDUiTZionefNuLFT9MuWBbWLO8kNCD8wEwY7NmpikQyeN8ebm2m03A=='
gateway:
  ip: 192.168.0.4

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
#    password: '{cipher}6420f0d7d63cfb4b186f8451ca8c5fdeadae7443aec0decf85c703b8c1886737'
    password: '{cipher}AQCzHwS4FuN5VbaxiLZDWXCVtUMhlqz6VSzCa/vLOkUd4kAuNjYIsemDALKSoCnrkFBauiXLgnVBn0zMWRolX0Dxx9p4fA+3coCt/sRbJ9LKF7WCAkUZK8Oawt6eAaRILCMOY3lAQdQDzGbiWxqNDJOW4KZdEMRYzncDgValFu8nbMBsWc++XHU8EeajhIuv4HUt56MVpPstKJtHW+40YDEnNbliBQ/gXnv7E8ARXnzIK+xJG2ObVz6zdJzb2ec+Miec8KduRt4iWIXTmPZMnTkCzMGCt9lplSeGsyY7gExNNV7NVzYHkQ3NIdm6FSTw5kt5lKXX0xcJJ+/ThvsFzf+1iscMpOxuE5XemynIlHfzYdwEEudA2rMjQojh4NqfNg8='

order_service:
#  url: http://127.0.0.1:8000/order-service/%s/orders
  url: http://ORDER-SERVICE/order-service/%s/orders